---
- name: Ensure groups exist
  group:
    name:  "{{ item }}"
    state: present
  with_items:
    - "{{ users | map(attribute='groups') | flatten | unique }}"
    - "{{ new_users | map(attribute='groups') | flatten | unique }}"

- name: Create user accounts
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    shell: "/bin/bash"
  with_items: 
  - "{{ users }}"
  - "{{ new_users }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', 'files/ssh-keys/'+ item.username + '.key.pub') }}"
  with_items: 
  - "{{ users }}"
  - "{{ new_users }}"

- name: Allow admin users to sudo without a password
  lineinfile:
    dest: "/etc/sudoers.d/admin" # path: in version 2.3
    state: "present"
    regexp: "^%admin"
    line: "%admin ALL=(ALL) NOPASSWD: ALL"
    create: true

- name: get the username running the deploy
  become: false
  command: whoami
  register: remote_username

- name: Delete the users
  user:
    name: "{{ item.username }}"
    state: absent
  when: remote_username.stdout != "{{ item.username }}"
  with_items:
  - "{{delete_users}}"
