---
- hosts: all
  tags: ntp
  vars:
     ansible_ssh_private_key_file: ../../../home/ansible/.ssh/id_rsa.pub

  become: true

  roles:
    - name: ansible-role-ntp

  post_tasks:
    - name: Reboot
      reboot:
      become: true
