---
- hosts: webservers
  become: yes

  tasks:
  - name: install latest httpd
    yum:
      name: httpd
      state: latest
  - name: write apache config file
    template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf

- hosts: databases
  remote_user: root

  tasks:
  - name: install latest postgres
    yum:
      name: postgres
      state: latest
  - name: start postgres service
    service:
      name: postgres
      state: started
